version: '1.0'

services:
  main:
    container_name: example
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      # - ${SERVER_PORT}:${SERVER_PORT}
      - 3000:3000
    command: npm run start:dev
    env_file:
      - .env
    networks:
      - webnet

networks:
  webnet:
volumes:
  pgdata:
